package: 0xf99aee9f21493e1590e7e5a9aea6f343a1f381031a04a732724871fc294be799
staking_object: 0xbe46180321c30aab2f8b3501e24048377287fa708018a5b7c2792b35fe339ee3

contexts:
  testnet:
    portal: trwal.app
    wallet_env: testnet
    walrus_context: testnet
    walrus_package: 0xd84704c17fc870b8764832c535aa6b11f21a95cd6f5bb38a9b07d2cf42220c66

  mainnet:
    portal: wal.app
    wallet_env: mainnet
    walrus_context: mainnet
    walrus_package: 0xfdc88f7d7cf30afab2f82e8380d11ee8f70efb90e863d1de8616fae1bb09ea77

default_context: testnet